### ISSUE TITLE
search_orders fails with uids greater than 60 characters.

### ISSUE THREAD

**Issue by nickstokes** [square/connect-python-sdk#104]
When using search_orders, occasionally a response will have uids larger than 60 characters and will cause the sdk to throw a ValueError:

    ValueError: Invalid value for 'uid', length must be less than '60'

Doing a manual API request with a problem order id shows that some returns seem to have uids in a different format greater than 60 characters, for example:

"uid": "AC1BA2CF-5C0C-4F2F-B92D-089ABFBED686:8ff2caa9-5c08-467a-a54c-a0c0eccee83c"

**Comment by StephenJosey** [comment]
Thanks for sharing! We're taking a look at this and will follow-up once we have more information.

**Comment by StephenJosey** [comment]
Closing this for now, this constraint has been removed in our new Python SDK: https://github.com/square/connect-python-sdk/issues/104

This will not be fixed in the old (this repo) SDK.
