### ISSUE TITLE
Managing orders

### ISSUE THREAD

**Issue by srknkrn** [square/connect-python-sdk#15]
Hello there,
When will it be possible to manage the orders through Connect API? 
Is there a road map that we can track the development progress of this feature?

**Comment by matanpaul** [comment]
Hi! 

Thanks so much for contacting us. Would love to hear more about what you are thinking when saying _ manage the orders_. Feel free to ping me on matan@squareup.com

**Comment by srknkrn** [comment]
Hi Matan,
Sorry for undetailed description. I want to complete orders with the API, but it looks like there is no support for managing order through the API.
https://docs.connect.squareup.com/api/connect/v1/index.html#navsection-orders
