### ISSUE TITLE
Getting Tips from the Transaction

### ISSUE THREAD

**Issue by kangnamtofu** [square/connect-python-sdk#16]
I don't think there is any way to separate out tip amount from the tendered value.
I wonder why tip is not part of the tender field?
Any way to get it or any plan to add it to the API?

**Comment by tristansokol** [comment]
Have you tried the [Retrieve Payment](https://docs.connect.squareup.com/api/connect/v1/#get-payments) endpoint? You should be able to get the tip amounts from there.

**Comment by kangnamtofu** [comment]
Can I mix use v1 and v2 together? My code is currently using v2 APIs.

**Comment by tristansokol** [comment]
yep! v1 & v2 can be used together.
