### ISSUE TITLE
Options for tuning connection pool size and other concurrency parameters on the underlying RESTClientObject?

### ISSUE THREAD

**Issue by sherbondy** [square/connect-python-sdk#51]
Hi there,

There doesn't seen to be a nice "ordained" way to tune the connection pool size of the RESTClientObject that the Python SDK depends on.

And, reading through the source code, I feel like there may be a mixup between the `num_pools=pools_size` parameter [currently in use](https://github.com/square/connect-python-sdk/blob/master/squareconnect/rest.py) and a *different* parameter to actually control the number of workers in a connection pool.

From reading the [urllib3 documentation](https://github.com/shazow/urllib3/blob/f9409436f83aeb79fbaf090181cd81b784f1b8ce/urllib3/poolmanager.py#L36), it appears that:

`num_pools` is a higher-order parameter that controls the number of connection pools via urllib3's `PoolManager` object, with each pool corresponding to requests issued to a specific distinct domain name (e.g. google.com vs. yahoo.com):

```
:param num_pools:
        Number of connection pools to cache before discarding the least
        recently used pool.
```

Whereas the `maxsize` parameter of an individual urllib3 `ConnectionPool` object [seems to actually control the number of concurrent & reusable request connections allowable for a given domain](https://github.com/shazow/urllib3/blob/f9409436f83aeb79fbaf090181cd81b784f1b8ce/urllib3/connectionpool.py#L125).

Since all of the Square Connect APIs are under the same domain (`connect.squareup.com`), wouldn't it make sense to expose, say in the Configuration object:

- `maxsize`
- `block`
- and maybe even the `retries` policy?

---

Is the expected "official" way of doing this to manually create:
- a custom `ApiClient` object 
  - with a custom `rest_client` object instance
    - with a custom `pools_manager` object instance with: `maxsize`, `block`, etc. all passed in as keyword arguments? 

And then to pass a customized `ApiClient` instance into the individual Connect API initializers?

That seems like a whole lot of custom!

It just feels a little messy relative to exposing these paramaters in a more first-class way via the `Configuration` object.

Would love to hear about the rationale behind this. Worried about people shooting themselves in the foot by configuring concurrency settings? Or maybe I am fundamentally misunderstanding something here?

Would be great to see the `Configuration` object support a catch-all parameter for open-ended kwargs to pass into the `RESTClientObject.pool_manager` attribute. Or an "ordained" subset of parameters such as `maxsize`, `block`, and `retries`.

This SDK is largely generated from the swagger codegen tool, right?
So maybe my beef is actually further upstream with the swagger project?

Thanks for taking the time to read this. 
Hope it is clear, and my apologies if I am fundamentally misunderstanding the affordances available for configuring concurrency via this SDK!

**Comment by sherbondy** [comment]
After some digging, I see that `swagger-codegen` does, in fact, support the `maxsize` attribute via the `Configuration` object. This change hit master on Sept. 18:

[https://github.com/swagger-api/swagger-codegen/commit/f3c41e866cd65296ddc9fa8a2de575de62d25fc2#diff-e74f661422557d69df8805a1b167c33a](https://github.com/swagger-api/swagger-codegen/commit/f3c41e866cd65296ddc9fa8a2de575de62d25fc2#diff-e74f661422557d69df8805a1b167c33a)

So I guess this will be partially resolved as soon as the next stable release of `swagger-codegen`, hooray!

**Comment by frojasg** [comment]
Thanks for reporting this problem!

**Comment by sherbondy** [comment]
Just a heads up, Swagger Codegen 2.3.0 was released in December with the aforementioned change to the python client included:
https://github.com/swagger-api/swagger-codegen/releases/tag/v2.3.0

**Comment by frojasg** [comment]
Thanks for the heads up! We've added it to our roadmap

**Comment by StephenJosey** [comment]
Hi all, closing this issue. Please move to our new Python SDK: https://github.com/square/square-python-sdk
