### ISSUE TITLE
Regen model to spec

### ISSUE THREAD

**Issue by lmorganjr** [square/connect-python-sdk#7]
Getting the following error in trying to run the sandbox code:

```
File "/home/ec2-user/misc/py3env/local/lib/python3.4/site-packages/squareconnect/models/location.py", line 177, in capabilities
    .format(capabilities, allowed_values)
ValueError: Invalid value for `capabilities` (['CREDIT_CARD_PROCESSING']), must be one of ['CREDIT_CARD_PROCESSING']
```

NOTE: An update was applied to the PHP library a few days back to fix this issue:

https://github.com/square/connect-php-sdk/commit/da05a9ca6820956cf51fe77c99713adf97743578#diff-4345e0819ed3f554767c2d710ba520b1

noted here: https://www.sellercommunity.com/t5/Developers-API/SDK-and-Sandbox-locations-quot-Invalid-value-for-capabilities/m-p/29717

**Comment by lmorganjr** [comment]
FYI...the Ruby connect code removed the same check: https://github.com/square/connect-ruby-sdk/commit/bb993e8c1dbc83ff3939168965330122bcd9e50b#diff-9e68b5563dc4f300cb8a14c3e473635f

**Comment by ti55987** [comment]
@lmorganjr  We have fixed the bug. Let us know if there is still issue in List Locations endpoint. Thanks
cc @tristansokol
