### ISSUE TITLE
renew token example

### ISSUE THREAD

**Issue by LukeAllen** [square/connect-python-sdk#76]
The docs don't explain how to avoid a "missing authorization header" error from the renew_token function. I figured it out by reading source code. Here's an example of how to set that header (this should be in the docs but isn't):

```
from squareconnect.models.renew_token_request import RenewTokenRequest
from squareconnect.apis.o_auth_api import OAuthApi
from squareconnect.api_client import ApiClient

oAuthApi=OAuthApi(ApiClient(header_name="Authorization", header_value="Client %s"%YOUR_APP_SECRET))
res=oAuthApi.renew_token(client_id=YOUR_APP_ID,
                             body=RenewTokenRequest(access_token=ACCESS_TOKEN_TO_RENEW))
print res.access_token
print res.expires_at
```

**Comment by StephenJosey** [comment]
Closing this issue. Please move to our new Python SDK: https://github.com/square/square-python-sdk
