### ISSUE TITLE
Why are there no product names in transactions?

### ISSUE THREAD

**Issue by srknkrn** [square/connect-python-sdk#8]
In order to integrate my system, I need to be able to determine which product is purchased in the squareup store. But I did not see anything about it in the API documentation. Can you help me with this?

**Comment by tristansokol** [comment]
Right now, transactions made via the API don't support itemization. E-commerce itemization is something we are actively working on, so keep a look out for its announcement.

**Comment by srknkrn** [comment]
Thank you for your response, and unfortunately I will do this through the Gmail API for now.
