### ISSUE TITLE
Backward incompatible change to handling access_token not mentioned in CHANGES.md

### ISSUE THREAD

**Issue by slinkp** [square/connect-python-sdk#83]
I found that after upgrading from 2.5.1 to 2.20181212.0 I was getting errors like this from `list_locations()`:

```
ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-length': '569', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'Strict-Transport-Security': 'max-age=631152000', 'Vary': 'Origin, Accept-Encoding', 'keep-alive': 'timeout=60', 'X-Permitted-Cross-Domain-Policies': 'none', 'Date': 'Mon, 21 Jan 2019 18:56:04 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json'})
HTTP response body: {"errors":[{"category":"AUTHENTICATION_ERROR","code":"UNAUTHORIZED","detail":"The `Authorization` http header of your request was malformed. The header value is expected to be of the format \"Bearer TOKEN\" (without quotation marks), where TOKEN is to be replaced with your access token (e.g. \"Bearer ABC123def456GHI789jkl0\"). For more information, see https://docs.connect.squareup.com/api/connect/v2/#requestandresponseheaders. If you are seeing this error message while using one of our officially supported SDKs, please report this to developers@squareup.com."}]}
```

Eventually I traced this to the method of passing in access_token having changed.
It used to be you would set it globally on `squareconnect.configuration.access_token`.
That no longer works and you have to set `api.api_client.configuration.access_token`.

This apparently changed sometime after 2.9.0

Should really be noted in the CHANGES.md file since it's a major backward incompatibility that breaks auth for anyone who upgrades.

I did see this: "Remove singleton constraint for configuration class. This is a minor breaking change to ApiClient and RESTClientObject initialization."

Not sure if that's about the same thing, but if so I don't think this is adequate notice, because  a) the fix requires changing every line of my code that instantiates a square api, and b) this doesn't tell the reader anything about what to *do*.
I only figured it out by re-reading the README and noticing the example had changed.

**Comment by StephenJosey** [comment]
Thanks for this feedback! We definitely will add more detail in the future. 

In the mean time, would you be interested in discussing how you use our SDK and how you handle upgrades so we (Square) can make this a better experience for everyone who uses our SDKs? If so, please create a support ticket (https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68) and reference this thread, and I'll be sure I get a hold of it so we can arrange a phone call. Thanks again!

**Comment by StephenJosey** [comment]
We have now updated our change log to reflect these changes. Thanks again for making us more aware!
