### ISSUE TITLE
Catalog Item Variation Docs Misplaced Fields

### ISSUE THREAD

**Issue by xarasco** [square/connect-python-sdk#95]
https://github.com/square/connect-python-sdk/blob/master/docs/CatalogItemVariation.md

The following are fields in list[ItemVariationLocationOverrides] rather than squareconnect.models.catalog_item_variation

track_inventory 
inventory_alert_type
inventory_alert_threshold 

Source: https://connect.squareup.com/v2/catalog/list?types=item_variation

{
            "type": "ITEM_VARIATION",
            "id": "somelongid",
            "updated_at": "2018-11-07T00:12:19.849Z",
            "version": 1541549539849,
            "is_deleted": false,
            "catalog_v1_ids": [
                {
                    "catalog_v1_id": "somelongerid",
                    "location_id": "somelocationid"
                }
            ],
            "present_at_all_locations": true,
            "item_variation_data": {
                "item_id": "anotherlongid",
                "name": "FTW - Navy",
                "sku": "",
                "ordinal": 4,
                "pricing_type": "FIXED_PRICING",
                "price_money": {
                    "amount": 2200,
                    "currency": "USD"
                },
                "location_overrides": [
                    {
                        "location_id": "somelocationid",
                        "track_inventory": false,
                        "inventory_alert_type": "NONE",
                        "inventory_alert_threshold": 0
                    },
                    {
                        "location_id": "somelocationid",
                        "track_inventory": false,
                        "inventory_alert_type": "NONE",
                        "inventory_alert_threshold": 0
                    }
                ],
                "service_duration": 0
            }
        },

**Comment by StephenJosey** [comment]
The fields:
```
track_inventory
inventory_alert_type
inventory_alert_threshold
```
exist in both the `CatalogItemVariation` and `ItemVariationLocationOverrides`. You would use the  former if you expect it to be for all locations, and you would use the latter if you want different rules for different locations. Please let me know if I'm misunderstanding, or if you have further questions.

**Comment by xarasco** [comment]
Ok.  Perhaps this group simply doesn't have anything set up with overrides that apply at all locations.  Thanks.

**Comment by StephenJosey** [comment]
Hi @xarasco the root level `CatalogItemVariation` applies to all locations. Use those fields if you want them to apply at all locations.
